import ts from 'typescript';
import {readFileSync,writeFileSync} from 'node:fs';
const source=readFileSync(new URL('../lib/rewards.ts',import.meta.url),'utf8').replace(/export /g,'').replace('structuredClone(current)','JSON.parse(JSON.stringify(current))');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2020,module:ts.ModuleKind.None}}).outputText;
// All reducer helpers are private to Apps Script: only classroomRpc is exposed.
writeFileSync(new URL('../apps-script/Model.gs',import.meta.url),'// Generated by npm run build. Do not edit.\nfunction model_(){\n'+js+'\nreturn {initialState,applyCommand,scores,redeemedScores,availableScores,redemptionCounts,seats};\n}\n');
